const publications = [
  {
    title: "The hijacking of a wheat <i>Exo70</i>-like protein by a fungal pathogen triggers disease",
    authors: "<u><strong>Singh G</strong></u>, Running KLD, Seneviratne S, Acharya K, Roth TM, Haugrud ARP, Zhang Z, Szabo-Hever A, Kumari P, McClean PE, Liu Z, Yang S, and Faris JD",
    journal: "<i>Nature Communication (Under Review)</i>",
    year: 2026,
    citations: 0,
    url: "https://doi.org/10.21203/rs.3.rs-8788414/v1",
    abstract: "Tan spot is an economically important fungal disease of wheat that occurs globally. In this necrotrophic pathosystem, pathogen effectors are recognized by wheat genes in an inverse gene-for-gene manner, leading to the hijacking of host defense mechanisms and ultimately disease susceptibility. Here, we identified the tan spot susceptibility gene <i>Tsc2</i> through positional cloning, mutagenesis, and transgenic complementation. <i>Tsc2</i> encodes a diverged form of the exocyst subunit Exo70FX15 that localizes to the nucleus and cytoplasm and does not interact directly with the fungal effector. A 21‑nucleotide deletion in <i>Tsc2</i> occurred in durum wheat more than a century ago and subsequently spread to common wheat through breeding practices, which allowed recognition of the pathogen effector and subsequent hijacking of the host immune system. We demonstrate that elimination of <i>Tsc2</i> through conventional breeding using a diagnostic marker or disruption of <i>Tsc2</i> by gene editing can be used to improve tan spot resistance in wheat.",
    citingPapers: []
  },
  {
    title: "Fluorescence-based absent allele-specific amplification (FAASA) for high-throughput detection of absent alleles",
    authors: "Running K, Seneviratne S, Zhang Z, <strong>Singh G</strong>, Fiedler J, and Faris JD",
    journal: "<i>Bio-protocol (Accepted; in press)</i>",
    year: 2026,
    citations: 0,
    url: "",
    abstract: "Accepted; <i>in press</i>. Abstract will be available soon.",
    citingPapers: []
  },
  {
    title: "Genetic analysis of a quantitative trait locus associated with resistance to the root-lesion nematode <i>Pratylenchus neglectus</i> in triticale",
    authors: "<strong>Singh G</strong>, Acharya K, Mumia B, Ranabhat S, Ojha E, Singh J, Gill U, Walkowiak S, Chawla HS, Li X, Faris JD, Liu Z, and Yan G",
    journal: "<i>Theoretical and Applied Genetics</i> 139(1):1-13",
    year: 2026,
    citations: 0,
    url: "https://doi.org/10.1007/s00122-025-05112-6",
    abstract: "Root-lesion nematode (<i>Pratylenchus neglectus</i>, RLN) poses a significant threat to global wheat production. High levels of RLN resistance are rare in wheat. Triticale, an amphiploid generated by combining wheat and rye genomes that naturally carries rye-derived defense alleles, offers an untapped reservoir of nematode resistance. Here, we evaluated the response to RLN in 137 recombinant inbred lines (RILs) derived from a cross between two triticale cultivars: Siskiyou (susceptible) and Villax St. Jose (resistant). Genotyping-by-sequencing identified 1,054 high-quality single-nucleotide polymorphism (SNP) markers, which, along with seven simple sequence repeat (SSR) markers, were assembled into 21 linkage groups covering the triticale genome. A single quantitative trait locus (QTL) on the rye-derived chromosome 5R was identified that explained approximately 20% of the phenotypic variance across experiments. A high-throughput Kompetitive allele-specific PCR (KASP) assay based on the most significant SNP marker was developed, providing a rapid genotyping platform for selecting the resistance allele and reducing reliance on labor-intensive phenotyping for P. neglectus resistance in triticale. This study reports the first mapped RLN-resistance QTL in triticale, laying the fundamental foundation for introgressing the 5R resistance allele into wheat via marker-assisted selection combined with chromosome engineering, thereby broadening the genetic basis for nematode resistance in cereal crops.",
    citingPapers: []
  },  
  {
    title: "Evaluation of field pea cultivars for resistance to pin nematode (<i>Paratylenchus nanus</i> type B) in North Dakota",
    authors: "Ojha E, <strong>Singh G</strong>, Plaisance A, and Yan GP",
    journal: "<i>Plant Disease</i>",
    year: 2026,
    citations: 1,
    url: "https://doi.org/10.1094/PDIS-02-25-0356-RE",
    abstract: "Pin nematodes (<i>Paratylenchus</i> spp.) are common plant-parasitic nematodes in North Dakota that can negatively impact field pea (<i>Pisum sativum</i>) production. These nematodes rely on a functional stylet to feed, which develops through molting from a non-feeding fourth-stage juvenile (J-4) into an adult. Understanding the role of host resistance and root exudates in triggering this molting process is crucial for effective nematode management. In this study, we evaluated 31 field pea cultivars for resistance to <i>P. nanus</i> type B in greenhouse experiments using naturally infested soil and investigated the influence of root exudates on J-4 molting under laboratory conditions. Reproductive factor (RF) was calculated as the final nematode population density divided by the initial density. Among the tested cultivars, six were classified as susceptible (Columbia, Carousel, Mystique, Flute, Banner, and Arcadia), twenty were moderately susceptible (DS Admiral, Ginny, Melrose, Korando, Capella, Bacurra, LG Amigo, CDC Striker, Granger, Spider, LG Sunrise, LG Koda, Fergie, SW Midas, Monarch, Nette, Hampton, Greenwood, K2, and Chrome), and five were moderately resistant (Matrix, Agassiz, Salamanca, Viper, and Aragorn). Additionally, root exudates from the susceptible cultivar Columbia induced molting up to 39% in J-4 nematodes, compared to only 6% in exudates from the moderately resistant cultivar Viper. This is the first report examining the effects of field pea root exudates on the molting of J-4 pin nematodes. Further studies on root exudate chemistry could provide deeper insights into host-nematode interactions. Overall, most cultivars supported nematode reproduction, underscoring the need for effective management strategies to mitigate nematode infestations.",
    citingPapers: [
      {
        title: "Advancing molecular diagnostics and resistance assessment of a new root-lesion nematode, <i>Pratylenchus dakotaensis</i> on soybean",
        authors: "Ranabhat S",
        journal: "<i>MS Thesis</i>, North Dakota State University, Fargo, ND, USA",
        year: 2025,
        url: "https://www.proquest.com/docview/3248170780/fulltextPDF/640077CA10604592PQ/1?accountid=6766&sourcetype=Dissertations%20&%20Theses"
      }
    ]
  },
  {
    title: "Genomic and Functional Characterization of the Tan Spot Susceptibility Gene <i>Tsc2</i> in Wheat",
    authors: "<strong>Singh, Gurminder</strong>",
    journal: "<i>PhD Thesis</i>, North Dakota State University, Fargo, ND, USA",
    year: 2025,
    citations: 3,
    url: "https://www.proquest.com/docview/3217054618?pq-origsite=gscholar&fromopenview=true&sourcetype=Dissertations%20&%20Theses",
    abstract: "Tan spot, caused by the necrotrophic fungus <i>Pyrenophora tritici-repentis</i>, continues to threaten global wheat production, sometimes reducing yields by over 50% under conducive conditions. The interaction between the fungal necrotrophic effector Ptr ToxB and the host susceptibility gene <i>Tsc2</i> initiates leaf chlorosis and drives disease progression. Although <i>Tsc2</i> was previously localized to chromosome arm 2BS, the underlying gene has not been identified. In this thesis, I used high-resolution genetic mapping, EMS mutagenesis, TILLING, and transgenic complementation to demonstrate that <i>Tsc2</i> is a member of an unconventional exocyst subunit encoded by the gene <i>TtExo70FX15</i>. Functional analyses revealed that <i>Tsc2</i> was broadly expressed in various wheat tissues but downregulated in leaves after Ptr ToxB exposure. Structural modeling and subcellular localization experiments suggest that Tsc2 has diverged from canonical exocyst functions, highlighting a unique “hijacking” scenario by a necrotrophic pathogen. Yeast two-hybrid assays revealed no direct binding between Tsc2 and Ptr ToxB, implying that additional host factors mediate susceptibility. Sequencing of 409 diverse wheat accessions uncovered five major <i>Tsc2</i> haplotypes. One canonical haplotype consistently correlated with sensitivity, whereas others often lacking a 21-nucleotide deletion or bearing nonsynonymous SNPs abolished or reduced Ptr ToxB-induced chlorosis. To support breeding applications, I developed a high-throughput marker (<i>fcp1066</i>) that specifically detected absent alleles of <i>Tsc2</i> associated with insensitivity. Validation in over 1,500 wheat lines confirmed its efficacy, opening avenues for marker-assisted selection aimed at eliminating this susceptibility gene from breeding pipelines. These findings provide insights into how necrotrophic effectors may exploit host exocyst components for disease development. By elucidating the role of <i>Tsc2</i> in Ptr ToxB susceptibility and establishing a rapid genotyping assay, this work offers a foundation for reducing tan spot severity in both durum and bread wheat, supporting more resilient wheat production.",
    citingPapers: [
      {
        title: "Improved reannotations of <i>Aegilops umbellulata</i> (PI 554389) genome and transcriptomics data provides candidates for leaf rust resistance for wheat improvement",
        authors: "Singh J, Gudi S, Maughan PJ, Gupta R, and Gill U",
        journal: "<i>Scientific Reports</i>",
        year: 2025,
        url: "https://doi.org/10.21203/rs.3.rs-7539367/v1"
      },
      {
        title: "Development of genomic resources and exploration of disease resistance in <i>Aegilops umbellulata</i> to improve the cultivated wheat",
        authors: "Singh, J",
        journal: "<i>PhD Thesis</i>, North Dakota State University, Fargo, ND, USA",
        year: 2025,
        url: "https://www.proquest.com/docview/3248177347/E98FD438024B4F25PQ/1?accountid=6766&sourcetype=Dissertations%20&%20Theses"
      },
      {
        title: "Genetic analysis of a quantitative trait locus associated with resistance to the root-lesion nematode <i>Pratylenchus neglectus</i> in triticale",
        authors: "Singh G, Acharya K, Mumia B, Ranabhat S, Ojha E, Singh J, Gill U, Walkowiak S, Chawla HS, Li X, Faris JD, Liu Z, and Yan G",
        journal: "<i>Theoretical and Applied Genetics</i>",
        year: 2026,
        url: "https://doi.org/10.1007/s00122-025-05112-6"
      }
    ]
  },  
  {
    title: "Development of diagnostic markers for the disease susceptibility gene <i>Tsn1</i> in wheat reveals novel resistance alleles and a new locus required for ToxA sensitivity",
    authors: "Running K, Acharya K, Roth T, <strong>Singh G</strong>, Szabo-Hever A, Haugrud A, Fiedler J, Friesen TL, and Faris JD",
    journal: "<i>Theoretical and Applied Genetics</i> 138(7):1-14",
    year: 2025,
    citations: 2,
    url: "https://doi.org/10.1007/s00122-025-04952-6",
    abstract: "The wheat <i>Tsn1</i> gene recognizes the necrotrophic effector ToxA, which is produced by three different necrotrophic fungal pathogens. A compatible <i>Tsn1</i>–ToxA interaction leads to host-induced responses that result in the development of disease. Therefore, marker-assisted elimination of functional <i>Tsn1</i> alleles is an effective strategy for the development of disease resistant varieties. To develop such markers, available wheat genome assemblies were used to compare gene and transposable element content in lines with and without <i>Tsn1</i> (<i>Tsn1</i>- and <i>Tsn1</i> +), revealing two conserved haplotypes. Because <i>Tsn1</i> is almost always absent in insensitive lines, Kompetitive allele-specific PCR (KASP) markers were designed in flanking syntenic regions of <i>Tsn1</i>- and <i>Tsn1</i> + assemblies. The KASP markers were validated in more than 1,500 diverse lines. The markers correctly predicted a ToxA-insensitive phenotype in 99.33–100% of the lines, but they were less effective at predicting a ToxA-sensitive phenotype (89.50–94.55%) due to 60 insensitive lines with sensitive marker alleles. Sequence analysis of <i>Tsn1</i> from these lines revealed that some were not transcribed and others contained point mutations. However, some carried and expressed the dominant <i>Tsn1</i> allele, and subsequent analysis of two such lines revealed a second locus controlling ToxA sensitivity on chromosome 2B, termed <i>Tsn1-B2</i>. Genetic mapping of <i>Tsn1-B2</i> in a biparental durum population defined the locus to a 4.8 cM region corresponding to 8.6 Mb in Svevo Rel 2.0. The markers presented here could be used for reliable and robust marker-assisted elimination of <i>Tsn1</i> in a high-throughput manner, furthering the development of wheat genetically resistant to multiple pathogens.",
    citingPapers: [
      {
        title: "Features of the relationship between the parasite and the host in the pathosystem “<i>Triticum aestivum</i> – <i>Pyrenophora tritici-repentis</i>”",
        authors: "Mironenko NV",
        journal: "<i>Plant Protection News (Vestnik Zashchity Rasteniy), 108:132-140</i>",
        year: 2025,
        url: "https://doi.org/10.31993/2308-6459-2025-108-3-17254"
      },
      {
        title: "Genetic analysis of a quantitative trait locus associated with resistance to the root-lesion nematode <i>Pratylenchus neglectus</i> in triticale",
        authors: "Singh G, Acharya K, Mumia B, Ranabhat S, Ojha E, Singh J, Gill U, Walkowiak S, Chawla HS, Li X, Faris JD, Liu Z, and Yan G",
        journal: "<i>Theoretical and Applied Genetics</i>",
        year: 2026,
        url: "https://doi.org/10.1007/s00122-025-05112-6"
      }
    ]
  },    
  {
    title: "Protein kinase-major sperm protein (PK-MSP) genes mediate recognition of the fungal necrotrophic effector SnTox3 to cause septoria nodorum blotch in wheat",
    authors: "Zhang Z, Running K, Seneviratne S, Haugrud A, Szabo-Hever A, <strong>Singh G</strong>, Holušová K, Molnár I, Doležel J, Friesen TL, and Faris JD",
    journal: "<i>Molecular Plant-Microbe Interactions</i> 38:315-327",
    year: 2025,
    citations: 2,
    url: "https://doi.org/10.1094/MPMI-10-24-0125-FI",
    abstract: "The wheat-Parastagonospora nodorum pathosystem has emerged as a model system for plant-necrotrophic fungal pathogen interactions. In this system, fungal necrotrophic effectors (NEs) are recognized by specific host genes in an inverse gene-for-gene manner to induce programmed cell death (PCD) and other host responses, which leads to disease. We previously cloned a wheat gene (Snn3-D1) encoding protein kinase (PK) and major sperm protein (MSP) domains that recognizes the P. nodorum NE SnTox3. Here, we identified an Snn3-D1 homoeolog (Snn3-B1) and a paralog (Snn3-B2) that also recognize SnTox3 leading to susceptibility. DNA sequence divergence of Snn3-B1 and Snn3-B2 and differences in transcriptional expression patterns and 3D protein conformation were associated with a more severe PCD response conferred by Snn3-B2 compared to Snn3-B1. Both Snn3 proteins were localized to the nucleus and cytoplasm in wheat protoplasts suggesting they may have acquired novel functions compared to previously characterized MSP domain-containing proteins in other species. Snn3-B2 was previously shown to govern osmotic stress and salt tolerance indicating that PK-MSP genes can act in plant defense responses to both biotic and abiotic stresses. Evaluation of a large collection of wheat lines showed that several alleles of each gene, including absent alleles, exist within the germplasm. Diagnostic markers were developed for the absent alleles of both genes, which will prove useful for marker-assisted selection in wheat to eliminate SnTox3 sensitivity and achieve better disease resistance.",
    citingPapers: [
      {
        title: "A viral brake on bloom: BYDV-GAV delays flowering via VOZ degradation",
        authors: "Prakash V, and Singh J",
        journal: "<i>Molecular Plant-Microbe Interactions</i>",
        year: 2025,
        url: "https://doi.org/10.1094/MPMI-05-25-0060-CM"
      },
      {
        title: "Fine grain: molecular, cellular, and genomic details of cereal crop diseases",
        authors: "Derevnina L, Krasileva KV, Schwessinger B, and Wilson RA",
        journal: "<i>Molecular Plant-Microbe Interactions</i>",
        year: 2025,
        url: "https://doi.org/10.1094/MPMI-04-25-0040-CM"
      }      
    ]
  },  
  {
    title: "Evaluation of durum and hard red spring wheat panels for sensitivity to necrotrophic effectors produced by <i>Parastagonospora nodorum</i>",
    authors: "Szabo-Hever A, Running K, Seneviratne S, <strong>Singh G</strong>, Zhang Z, Haugrud A, Maccaferri M, Tuberosa R, Friesen TL, Xu SS, and Faris JD",
    journal: "<i>Plant Disease</i> 109:851-861",
    year: 2025,
    citations: 3,
    url: "https://doi.org/10.1094/PDIS-05-24-0990-RE",
    abstract: "<strong>Abstract:</strong> Septoria nodorum blotch is an important disease of both durum and hard red spring wheat (HRSW) worldwide. The disease is caused by the necrotrophic fungal pathogen Parastagonospora nodorum when compatible gene-for-gene interactions occur between pathogen-produced necrotrophic effectors (NEs) and corresponding host sensitivity genes. To date, nine sensitivity gene-NE interactions have been identified, but there is little information available regarding their overall frequency in durum and HRSW. Here, we infiltrated a global HRSW panel (HRSWP) and the Global Durum Panel (GDP) with P. nodorum NEs SnToxA, SnTox1, SnTox267, SnTox3, and SnTox5. Frequencies of sensitivity to SnTox1 and SnTox5 were higher in durum compared to HRSW and vice versa for SnTox267 and SnTox3. Strong associations for the known sensitivity loci <i>Tsn1</i>, <i>Snn1</i>, <i>Snn2</i>, <i>Snn3</i>, <i>Snn5</i>, and <i>Snn7</i> along with potentially novel sensitivity loci on chromosome arms 7DS and 3BL associated with SnToxA and SnTox267, respectively, were identified in the HRSWP. In the GDP, <i>Snn1</i>, <i>Snn3</i>, and <i>Snn5</i> were identified along with novel loci associated with sensitivity to SnTox267 on chromosome arms 2AS, 2AL, and 6AS and with SnTox5 sensitivity on 2BS and 7BL. These results reveal additional NE sensitivity loci beyond those previously described demonstrating a higher level of genetic complexity of the wheat-<i>P. nodorum</i> system than previously thought. Knowledge regarding the prevalence and genomic locations of SNB susceptibility genes in HRSW and durum will prove useful for developing efficient breeding strategies and improving varieties for SNB resistance.",
    citingPapers: [
      {
        title: "Genomic and functional characterization of the tan spot susceptibility gene <i>Tsc2</i> in wheat",
        authors: "Singh, Gurminder",
        journal: "<i>PhD Thesis</i>, North Dakota State University, Fargo, ND, USA",
        year: 2025,
        url: "https://www.proquest.com/docview/3217054618?pq-origsite=gscholar&fromopenview=true&sourcetype=Dissertations%20&%20Theses"
      },
      {
        title: "Development of diagnostic markers for the disease susceptibility gene <i>Tsn1</i> in wheat reveals novel resistance alleles and a new locus required for ToxA sensitivity",
        authors: "Running K, Acharya K, Roth T, Singh G, Szabo-Hever A, Haugrud A, Fiedler J, Friesen TL, and Faris JD",
        journal: "<em>Theoretical and Applied Genetics</em>",
        year: 2025,
        url: "https://doi.org/10.1007/s00122-025-04952-6"
      },
      {
        title: "Protein kinase-major sperm protein (PK-MSP) genes mediate recognition of the fungal necrotrophic effector SnTox3 to cause septoria nodorum blotch in wheat",
        authors: "Zhang Z, Running K, Seneviratne S, Haugrud A, Szabo-Hever A, Singh G, Holušová K, Molnár I, Doležel J, Friesen TL, and Faris JD",
        journal: "<em>Molecular Plant-Microbe Interactions</em>",
        year: 2025,
        url: "https://doi.org/10.1094/MPMI-10-24-0125-FI"
      }
    ]
  },
  {
    title: "Evolution, diversity, and function of the disease susceptibility gene <i>Snn1</i> in wheat",
    authors: "Seneviratne S, Shi G, Szabo-Hever A, Zhang Z, Haugrud A, Running K, <strong>Singh G</strong>, Nandety R, Fiedler J, McClean PE, Xu SS, Friesen TL, and Faris JD",
    journal: "<i>The Plant Journal</i> 119:1720-1736",
    year: 2024,
    citations: 6,
    url: "https://onlinelibrary.wiley.com/doi/abs/10.1111/tpj.16879",
    abstract: "<strong>Abstract:</strong> Septoria nodorum blotch (SNB), caused by <i>Parastagonospora nodorum</i>, is a disease of durum and common wheat initiated by the recognition of pathogen-produced necrotrophic effectors (NEs) by specific wheat genes. The wheat gene Snn1 was previously cloned, and it encodes a wall-associated kinase that directly interacts with the NE SnTox1 leading to programmed cell death and ultimately the development of SNB. Here, sequence analysis of <i>Snn1</i> from 114 accessions including diploid, tetraploid, and hexaploid wheat species revealed that some wheat lines possess two copies of Snn1 (designated <i>Snn1-B1</i> and <i>Snn1-B2</i>) approximately 120 kb apart. <i>Snn1-B2</i> evolved relatively recently as a paralog of <i>Snn1-B1</i>, and both genes have undergone diversifying selection. Three point mutations associated with the formation of the first SnTox1-sensitive <i>Snn1-B1</i> allele from a primitive wild wheat were identified. Four subsequent and independent SNPs, three in <i>Snn1-B1</i> and one in <i>Snn1-B2</i>, converted the sensitive alleles to insensitive forms. Protein modeling indicated these four mutations could abolish Snn1–SnTox1 compatibility either through destabilization of the Snn1 protein or direct disruption of the protein–protein interaction. A high-throughput marker was developed for the absent allele of Snn1, and it was 100% accurate at predicting SnTox1-insensitive lines in both durum and spring wheat. Results of this study increase our understanding of the evolution, diversity, and function of Snn1-B1 and Snn1-B2 genes and will be useful for marker-assisted elimination of these genes for better host resistance.",
    citingPapers: [
      {
        title: "Genetic analysis of a quantitative trait locus associated with resistance to the root-lesion nematode <i>Pratylenchus neglectus</i> in triticale",
        authors: "Singh G, Acharya K, Mumia B, Ranabhat S, Ojha E, Singh J, Gill U, Walkowiak S, Chawla HS, Li X, Faris JD, Liu Z, and Yan G",
        journal: "<i>Theoretical and Applied Genetics</i>",
        year: 2026,
        url: "https://doi.org/10.1007/s00122-025-05112-6"
      },
      {
        title: "Genomic and functional characterization of the tan spot susceptibility gene <i>Tsc2</i> in wheat",
        authors: "Singh, Gurminder",
        journal: "<i>PhD Thesis</i>, North Dakota State University, Fargo, ND, USA",
        year: 2025,
        url: "https://www.proquest.com/docview/3217054618?pq-origsite=gscholar&fromopenview=true&sourcetype=Dissertations%20&%20Theses"
      },
      {
        title: "Development of diagnostic markers for the disease susceptibility gene <i>Tsn1</i> in wheat reveals novel resistance alleles and a new locus required for ToxA sensitivity",
        authors: "Running K, Acharya K, Roth T, Singh G, Szabo-Hever A, Haugrud A, Fiedler J, Friesen TL, and Faris JD",
        journal: "<em>Theoretical and Applied Genetics</em>",
        year: 2025,
        url: "https://doi.org/10.1007/s00122-025-04952-6"
      },
      {
        title: "Protein kinase-major sperm protein (PK-MSP) genes mediate recognition of the fungal necrotrophic effector SnTox3 to cause septoria nodorum blotch in wheat",
        authors: "Zhang Z, Running K, Seneviratne S, Haugrud A, Szabo-Hever A, Singh G, Holušová K, Molnár I, Doležel J, Friesen TL, and Faris JD",
        journal: "<em>Molecular Plant-Microbe Interactions</em>",
        year: 2025,
        url: "https://doi.org/10.1094/MPMI-10-24-0125-FI"
      },
      {
        title: "Evaluation of durum and hard red spring wheat panels for sensitivity to necrotrophic effectors produced by <i>Parastagonospora nodorum</i>",
        authors: "Szabo-Hever A, Running K, Seneviratne S, Singh G, Zhang Z, Haugrud A, Maccaferri M, Tuberosa R, Friesen TL, Xu SS, Faris JD",
        journal: "<em>Plant Disease</em>",
        year: 2024,
        url: "https://doi.org/10.1094/PDIS-05-24-0990-RE"
      },
      {
        title: "Association mapping of tan spot and septoria nodorum blotch resistance in cultivated emmer wheat",
        authors: "Lhamo D, Sun Q, Friesen TL, Karmacharya A, Li X, Fiedler J, Faris JD, Xia G, Luo M, Gu Y, Liu Z, Xu SS",
        journal: "<em>Theoretical and Applied Genetics</em>",
        year: 2024,
        url: "https://doi.org/10.1007/s00122-024-04700-2"
      }
    ]
  },
  {
    title: "Evaluation of wheat cultivars and germplasm lines for resistance to <i>Pratylenchus neglectus</i> populations collected in North Dakota",
    authors: "<strong>Singh G</strong>, KC A, Sandhu KS, Friskop AJ, Liu Z, and Yan GP",
    journal: "<i>Plant Disease</i> 117:3817-3824",
    year: 2023,
    citations: 7,
    url: "https://apsjournals.apsnet.org/doi/abs/10.1094/PDIS-03-23-0590-RE",
    abstract: "<strong>Abstract:</strong> Root-lesion nematode (RLN; <i>Pratylenchus neglectus</i>) is a migratory endoparasite and a major soilborne pathogen that affects wheat (<i>Triticum</i> spp.) production worldwide. Genetic resistance is one of the most economical and effective ways to manage <i>P. neglectus</i> in wheat. This study evaluated 37 local cultivars and germplasm lines in seven greenhouse experiments, including 26 hexaploid wheat, six durum wheat, two synthetic hexaploid wheat, one emmer wheat, and two triticale for <i>P. neglectus</i> resistance from 2016 to 2020. North Dakota field soils infested with two RLN populations (350 to 1,125 nematodes per kilogram of soil) were used for resistance screening under controlled greenhouse conditions. The final nematode population density for each cultivar and line was counted under the microscope to categorize the resistance ranking of these entries as resistant, moderately resistant, moderately susceptible, and susceptible. Out of the 37 cultivars and lines, one was classified as resistant (Brennan); 18 were moderately resistant (Divide, Carpio, Prosper, Advance, Alkabo, SY Soren, Barlow, Bolles, Select, Faller, Briggs, WB Mayville, SY Ingmar, W7984, PI 626573, Ben, Grandin, and Villax St. Jose); 11 were moderately susceptible; and seven were susceptible to <i>P. neglectus</i>. The resistant to moderately resistant lines identified in this study could be used in breeding programs after the resistance genes or loci are further elucidated. This research provides valuable information about <i>P. neglectus</i> resistance among wheat and triticale cultivars used in the Upper Midwest region of the United States.",
    citingPapers: [
      {
        title: "Accelerated breeding in bajra using genomic approaches",
        authors: "Kashyap R, Saini DK, Sandhu SS, Puri H, Ahmed S, Singh J, Sandhu K, and Kapoor R",
        journal: "In: Wani SH, Gosal SS (eds) <i>Accelerated Plant Breeding</i>, Volume 5. Springer, Cham.",
        year: 2025,
        url: "https://doi.org/10.1007/978-3-032-04527-0_4"
      },
      {
        title: "Genetic analysis of a quantitative trait locus associated with resistance to the root-lesion nematode <i>Pratylenchus neglectus</i> in triticale",
        authors: "Singh G, Acharya K, Mumia B, Ranabhat S, Ojha E, Singh J, Gill U, Walkowiak S, Chawla HS, Li X, Faris JD, Liu Z, and Yan G",
        journal: "<i>Theoretical and Applied Genetics</i>",
        year: 2026,
        url: "https://doi.org/10.1007/s00122-025-05112-6"
      },
      {
        title: "Advancing molecular diagnostics and resistance assessment of a new root-lesion nematode, <i>Pratylenchus dakotaensis</i> on soybean",
        authors: "Ranabhat S",
        journal: "<i>MS Thesis</i>, North Dakota State University, Fargo, ND, USA",
        year: 2025,
        url: "https://www.proquest.com/docview/3248170780/fulltextPDF/640077CA10604592PQ/1?accountid=6766&sourcetype=Dissertations%20&%20Theses"
      },
      {
        title: "Evaluation of field pea cultivars for resistance to pin nematode (<i>Paratylenchus nanus</i> type B) in North Dakota",
        authors: "Ojha E, Singh G, Plaisance A, and Yan GP",
        journal: "<em>Plant Disease</em>",
        year: 2026,
        url: "https://doi.org/10.1094/PDIS-02-25-0356-RE"
      },
      {
        title: "Genomic and functional characterization of the tan spot susceptibility gene <i>Tsc2</i> in wheat",
        authors: "Singh, Gurminder",
        journal: "<i>PhD Thesis</i>, North Dakota State University, Fargo, ND, USA",
        year: 2025,
        url: "https://www.proquest.com/docview/3217054618?pq-origsite=gscholar&fromopenview=true&sourcetype=Dissertations%20&%20Theses"
      },
      {
        title: "Reproduction and molecular detection of plant-parasitic nematodes associated with potato",
        authors: "Goraya M",
        journal: "<i>MS Thesis, North Dakota State University, Fargo, ND, USA</i>",
        year: 2023,
        url: "https://www.proquest.com/openview/7d141f2e1f4a10955286fc9bf10beab4/1?pq-origsite=gscholar&cbl=18750&diss=y"
      },
      {
        title: "Molecular characterization of pin nematodes and evaluation of resistance in field pea cultivars",
        authors: "Ojha E",
        journal: "<i>MS Thesis, North Dakota State University, Fargo, ND, USA</i>",
        year: 2023,
        url: "https://www.proquest.com/openview/d20a446716a376dad835851bf2959cf6/1?pq-origsite=gscholar&cbl=18750&diss=y"
      }
    ]
  },
  {
    title: "Association mapping of resistance to tan spot in the Global Durum Panel",
    authors: "Szabo-Hever A, <strong>Singh G</strong>, Haugrud A, Running K, Seneviratne S, Zhang Z, Shi G, Bassi F, Maccaferri M, Cattivelli L, Tuberosa R, Friesen TL, Liu Z, Xu SS, and Faris JD",
    journal: "<i>Phytopathology</i> 113:1967-1978",
    year: 2023,
    citations: 10,
    url: "https://apsjournals.apsnet.org/doi/abs/10.1094/PHYTO-02-23-0043-R",
    abstract: "<strong>Abstract:</strong> Tan spot, caused by the necrotrophic fungal pathogen <i>Pyrenophora tritici-repentis</i> (<i>Ptr</i>), is an important disease of durum and common wheat worldwide. Compared with common wheat, less is known about the genetics and molecular basis of tan spot resistance in durum wheat. We evaluated 510 durum lines from the Global Durum Wheat Panel (GDP) for sensitivity to the necrotrophic effectors (NEs) Ptr ToxA and Ptr ToxB and for reaction to Ptr isolates representing races 1 to 5. Overall, susceptible durum lines were most prevalent in South Asia, the Middle East, and North Africa. Genome-wide association analysis showed that the resistance locus <i>Tsr7</i> was significantly associated with tan spot caused by races 2 and 3, but not races 1, 4, or 5. The NE sensitivity genes <i>Tsc1</i> and <i>Tsc2</i> were associated with susceptibility to Ptr ToxC- and Ptr ToxB-producing isolates, respectively, but <i>Tsn1</i> was not associated with tan spot caused by Ptr ToxA-producing isolates, which further validates that the <i>Tsn1</i>−Ptr ToxA interaction does not play a significant role in tan spot development in durum. A unique locus on chromosome arm 2AS was associated with tan spot caused by race 4, a race once considered avirulent. A novel trait characterized by expanding chlorosis leading to increased disease severity caused by the Ptr ToxB-producing race 5 isolate DW5 was identified, and this trait was governed by a locus on chromosome 5B. We recommend that durum breeders select resistance alleles at the <i>Tsr7</i>, <i>Tsc1</i>, <i>Tsc2</i>, and the chromosome 2AS loci to obtain broad resistance to tan spot.",
    citingPapers: [
      {
        title: "Genetic gains in durum wheat (<i>Triticum turgidum</i> ssp. <i>durum</i>) across the globe: yield, quality and adapting for variable weather patterns.",
        authors: "Achilli AL, Avci MI, Haile TA, Martínez-Peña R, and Peters Haugrud, AR",
        journal: "<i>Plant Breeding</i>",
        year: 2025,
        url: "https://doi.org/10.1111/pbr.70029"
      },
      {
        title: "Genomic and functional characterization of the tan spot susceptibility gene <i>Tsc2</i> in wheat",
        authors: "Singh Gurminder",
        journal: "<i>PhD Thesis</i>, North Dakota State University, Fargo, ND, USA",
        year: 2025,
        url: "https://www.proquest.com/docview/3217054618?pq-origsite=gscholar&fromopenview=true&sourcetype=Dissertations%20&%20Theses"
      },
      {
        title: "Development of diagnostic markers for the disease susceptibility gene <i>Tsn1</i> in wheat reveals novel resistance alleles and a new locus required for ToxA sensitivity",
        authors: "Running K, Acharya K, Roth T, Singh G, Szabo-Hever A, Haugrud A, Fiedler J, Friesen TL, and Faris JD",
        journal: "<em>Theoretical and Applied Genetics</em>",
        year: 2025,
        url: "https://doi.org/10.1007/s00122-025-04952-6"
      },
      {
        title: "Molecular mapping of a novel tan spot susceptibility gene in durum wheat",
        authors: "Roth TM",
        journal: "<i>MS Thesis, North Dakota State University, Fargo, ND, USA</i>",
        year: 2024,
        url: "https://www.proquest.com/docview/3158247605?fromopenview=true&pq-origsite=gscholar&sourcetype=Dissertations%20&%20Theses"
      },
      {
        title: "Evaluation of durum and hard red spring wheat panels for sensitivity to necrotrophic effectors produced by <i>Parastagonospora nodorum</i>",
        authors: "Szabo-Hever A, Running K, Seneviratne S, Singh G, Zhang Z, Haugrud A, Maccaferri M, Tuberosa R, Friesen TL, Xu SS, Faris JD",
        journal: "<em>Plant Disease</em>",
        year: 2024,
        url: "https://doi.org/10.1094/PDIS-05-24-0990-RE"
      },
      {
        title: "Evolution, diversity, and function of the disease susceptibility gene <i>Snn1</i> in wheat",
        authors: "Seneviratne S, Shi G, Szabo-Hever A, Zhang Z, Haugrud A, Running K, <strong>Singh G</strong>, Nandety R, Fiedler J, McClean PE, Xu SS, Friesen TL, Faris JD",
        journal: "<em>Biorxiv, 2024 - biorxiv.org</em>",
        year: 2024,
        url: "https://doi.org/10.1111/tpj.16879"
      },
      {
        title: "Association mapping of tan spot and septoria nodorum blotch resistance in cultivated emmer wheat",
        authors: "Lhamo D, Sun Q, Friesen TL, Karmacharya A, Li X, Fiedler J, Faris JD, Xia G, Luo M, Gu Y, Liu Z, Xu SS",
        journal: "<em>Theoretical and Applied Genetics</em>",
        year: 2024,
        url: "https://doi.org/10.1007/s00122-024-04700-2"
      },
      {
        title: "Evolution, diversity, function, and marker-based elimination of the disease susceptibility gene <i>Snn1</i> in wheat",
        authors: "Seneviratne S, Shi G, Szabo-Hever A, Zhang Z, Haugrud A, Running K, Singh G, Nandety R, Fiedler J, McClean PE, Xu SS, Friesen TL, Faris JD",
        journal: "<em>The Plant Journal</em>",
        year: 2024,
        url: "https://doi.org/10.1101/2024.01.24.577084"
      },
      {
        title: "Marker assisted backcross introgression of a race non-specific QTL to develop durum wheat lines with improved tan spot resistance",
        authors: "Acharya N",
        journal: "<i>MS Thesis, North Dakota State University, Fargo, ND, USA</i>",
        year: 2024,
        url: "https://www.proquest.com/docview/3106536557?fromopenview=true&pq-origsite=gscholar&sourcetype=Dissertations%20&%20Theses"
      },
      {
        title: "Genome-wide association mapping of resistance to the foliar diseases septoria nodorum blotch and tan spot in a global winter wheat collection",
        authors: "Haugrud A, Shi G, Seneviratne S, Running K, Zhang Z, <strong>Singh G</strong>, Szabo-Hever A, Acharya K, Friesen TL, Liu Z, Faris JD",
        journal: "<em>Molecular Breeding</em>",
        year: 2023,
        url: "https://doi.org/10.1007/s11032-023-01400-5"
      }
    ]
  },
  {
    title: "Genome-wide association mapping of resistance to the foliar diseases septoria nodorum blotch and tan spot in a global winter wheat collection",
    authors: "Haugrud A, Shi G, Seneviratne S, Running K, Zhang Z, <strong>Singh G</strong>, Szabo-Hever A, Acharya K, Friesen TL, Liu Z, and Faris JD",
    journal: "<i>Molecular Breeding</i> 43:54",
    year: 2023,
    citations: 13,
    url: "https://link.springer.com/article/10.1007/s11032-023-01400-5",
    abstract: "<strong>Abstract:</strong> Septoria nodorum blotch (SNB) and tan spot, caused by the necrotrophic fungal pathogens <i>Parastagonospora nodorum</i> and <i>Pyrenophora tritici-repentis</i>, respectively, often occur together as a leaf spotting disease complex on wheat (<i>Triticum aestivum</i> L.). Both pathogens produce necrotrophic effectors (NEs) that contribute to the development of disease. Here, genome-wide association analysis of a diverse panel of 264 winter wheat lines revealed novel loci on chromosomes 5A and 5B associated with sensitivity to the NEs SnTox3 and SnTox5 in addition to the known sensitivity genes for NEs Ptr/SnToxA, SnTox1, SnTox3, and SnTox5. Sensitivity loci for SnTox267 and Ptr ToxB were not detected. Evaluation of the panel with five P. nodorum isolates for SNB development indicated the Snn3-SnTox3 and Tsn1-SnToxA interactions played significant roles in disease development along with additional QTL on chromosomes 2A and 2D, which may correspond to the Snn7-SnTox267 interaction. For tan spot, the Tsc1-Ptr ToxC interaction was associated with disease caused by two isolates, and a novel QTL on chromosome 7D was associated with a third isolate. The Tsn1-ToxA interaction was associated with SNB but not tan spot. Therefore some, but not all, of the previously characterized host gene-NE interactions in these pathosystems play significant roles in disease development in winter wheat. Based on these results, breeders should prioritize the selection of resistance alleles at the <i>Tsc1</i>, <i>Tsn1</i>, <i>Snn3</i>, and <i>Snn7</i> loci as well as the 2A and 7D QTL to obtain good levels of resistance to SNB and tan spot in winter wheat.",
    citingPapers: [
      {
        title: "Fair-weather friends: Unequal partnerships between <i>Parastagonospora nodorum</i> and <i>Pyrenophora tritici-repentis</i> define disease dynamics in wheat",
        authors: "Lenzo LV, John E, Bradley J, Thomas G, Bennett D, Tan K",
        journal: "<i>bioRxiv Preprint</i>",
        year: 2025,
        url: "https://doi.org/10.1101/2025.10.09.681059"
      },
      {
        title: "Performance and stability of winter wheat cultivars to <i>Stagonospora nodorum</i> blotch epidemics in multi-environment trials",
        authors: "Garnica VC, Shalizi MN, and Ojiambo PS",
        journal: "<i>Phytopathology</i>",
        year: 2025,
        url: "https://doi.org/10.1094/PHYTO-12-24-0398-R"
      },
      {
        title: "Identification and validation of a major QTL on chromosome 2A for wheat-<i>Parastagonospora nodorum</i> interactions",
        authors: "Li C, He X, Ma J, and Singh PK",
        journal: "<i>Phytopathology Research</i>",
        year: 2025,
        url: "https://doi.org/10.1186/s42483-025-00371-z"
      },
      {
        title: "Genetics of host resistance and pathogen virulence in wheat bacterial leaf streak",
        authors: "Manan F",
        journal: "<i>PhD Thesis</i>, North Dakota State University, Fargo, ND, USA",
        year: 2025,
        url: "https://www.proquest.com/docview/3248171177?pq-origsite=gscholar&fromopenview=true&sourcetype=Dissertations%20&%20Theses"
      },
      {
        title: "Genomic and functional characterization of the tan spot susceptibility gene <i>Tsc2</i> in wheat",
        authors: "Singh Gurminder",
        journal: "<i>PhD Thesis</i>, North Dakota State University, Fargo, ND, USA",
        year: 2025,
        url: "https://www.proquest.com/docview/3217054618?pq-origsite=gscholar&fromopenview=true&sourcetype=Dissertations%20&%20Theses"
      },
      {
        title: "ToxA and ToxB have minimal effect on tan spot epidemics of spring wheat in the Nordics",
        authors: "Johansson A, Karisto P, Latvala S, See PT, Lillemo M, Hansen PB, and Jalli M",
        journal: "<i>European Journal of Plant Pathology</i>",
        year: 2025,
        url: "https://doi.org/10.21203/rs.3.rs-6547012/v1"
      },
      {
        title: "Development of diagnostic markers for the disease susceptibility gene <i>Tsn1</i> in wheat reveals novel resistance alleles and a new locus required for ToxA sensitivity",
        authors: "Running K, Acharya K, Roth T, Singh G, Szabo-Hever A, Haugrud A, Fiedler J, Friesen TL, and Faris JD",
        journal: "<em>Theoretical and Applied Genetics</em>",
        year: 2025,
        url: "https://doi.org/10.1007/s00122-025-04952-6"
      },
      {
        title: "Evaluation of durum and hard red spring wheat panels for sensitivity to necrotrophic effectors produced by <i>Parastagonospora nodorum</i>",
        authors: "Szabo-Hever A, Running K, Seneviratne S, Singh G, Zhang Z, Haugrud A, Maccaferri M, Tuberosa R, Friesen TL, Xu SS, Faris JD",
        journal: "<em>Plant Disease</em>",
        year: 2024,
        url: "https://doi.org/10.1094/PDIS-05-24-0990-RE"
      },
      {
        title: "Association mapping of tan spot and septoria nodorum blotch resistance in cultivated emmer wheat",
        authors: "Lhamo D, Sun Q, Friesen TL, Karmacharya A, Li X, Fiedler J, Faris JD, Xia G, Luo M, Gu Y, Liu Z, Xu SS",
        journal: "<em>Theoretical and Applied Genetics</em>",
        year: 2024,
        url: "https://doi.org/10.1007/s00122-024-04700-2"
      },
      {
        title: "Interaction of wheat-<i>Parastagonospora nodorum</i> isolates: Exploring host susceptibility and fungal virulence",
        authors: "Choupannejad R, Sharifnabi B, Collemare J, Massah A, Gholami J, Mehrabi R",
        journal: "<em>Physiological and Molecular Plant Pathology</em>",
        year: 2024,
        url: "https://doi.org/10.1016/j.pmpp.2023.102235"
      },
      {
        title: "Survival of the Exserohilum rostratum causal leaf spot of wheat and dissemination, infection behaviour from flower-seed-seedlings",
        authors: "Korra T, P. T, Chandra R",
        journal: "<em>Cereal Research Communications</em>",
        year: 2024,
        url: "https://doi.org/10.1007/s42976-024-00575-7"
      },
      {
        title: "Host susceptibility and fungal virulence in the wheat-<i>Parastagonospora nodorum</i> interactions",
        authors: "Choupannejad R, Sharifnabi B, Collemare J, Massah A, Gholami J, Mehrabi R",
        journal: "<em>Research Square</em> (Preprint)",
        year: 2023,
        url: "https://doi.org/10.21203/rs.3.rs-3198290/v1"
      },
      {
        title: "Intelligent reprogramming of wheat for enhancement of fungal and nematode disease resistance using advanced molecular techniques",
        authors: "Jabran M, Ali MA, Zahoor A, Muhae-Ud-Din G, Liu T, Chen W, Gao L",
        journal: "<em>Frontiers in Plant Science</em>",
        year: 2023,
        url: "https://doi.org/10.3389/fpls.2023.1132699"
      }
    ]
  },
  {
    title: "Resistance screening and QTL mapping in wheat and triticale against root-lesion nematode",
    authors: "<strong>Singh, Gurminder</strong>",
    journal: "<i>MS Thesis</i>, North Dakota State University, Fargo, ND, USA",
    year: 2020,
    citations: 5,
    url: "https://www.proquest.com/openview/f06d4867c07d7e3ea21b2e2a9b5b6cb6/1?pq-origsite=gscholar&cbl=18750&diss=y",
    abstract: "<strong>Abstract:</strong> Root-lesion nematode (RLN, <i>Pratylenchus neglectus</i>) invades the roots of wheat and causes yield losses throughout the world. Genetic resistance is the most economical and effective means to manage RLNs. The objective of this study were to identify source of resistance to RLN in a small collection of wheat germplasm and to map quantitative trait loci (QTL) associated with RLN resistance in two; one wheat and one triticale recombinant inbred line (RIL) populations. Out of wheat lines, three were resistant, including hard red spring wheat cultivars Brennan, SY Ingmar, and SY Soren. A number of genomic regions in wheat and rye were identified as QTL for RLN resistance. My research provides a better understanding of the genetic basis of <i>P. neglectus</i> resistance and important tools for RLN resistance breeding.",
    citingPapers: [
      {
        title: "Reproduction and molecular detection of plant-parasitic nematodes associated with potato",
        authors: "Goraya M",
        journal: "<em>MS Thesis, North Dakota State University, Fargo, ND, USA</em>",
        year: 2023,
        url: "https://www.proquest.com/openview/7d141f2e1f4a10955286fc9bf10beab4/1?pq-origsite=gscholar&cbl=18750&diss=y"
      },
      {
        title: "Evaluation of wheat cultivars and germplasm lines for resistance to <i>Pratylenchus neglectus</i> populations collected in North Dakota",
        authors: "Singh G, KC A, Sandhu KS, Friskop AJ, Liu Z, Yan GP",
        journal: "<em>Plant Disease</em>",
        year: 2023,
        url: "https://apsjournals.apsnet.org/doi/abs/10.1094/PDIS-03-23-0590-RE"
      },
      {
        title: "Population Development of the Root-Lesion Nematode <i>Pratylenchus dakotaensis</i> on Soybean Cultivars",
        authors: "Chowdhury IA",
        journal: "<em>Plant Disease</em>",
        year: 2022,
        url: "https://apsjournals.apsnet.org/doi/full/10.1094/PDIS-11-21-2444-RE"
      },
      {
        title: "Wheat Landraces Versus Resistance to Biotic and Abiotic Stresses",
        authors: "Shlibak A, Örgeç M, Zencirci N",
        journal: "<em>In book: Wheat Landraces. (Edition-1) Chapter-10</em>",
        year: 2021,
        url: "https://link.springer.com/chapter/10.1007/978-3-030-77388-5_10"
      },
      {
        title: "Plant-Parasitic Nematodes on Corn (<i>Zea mays</i> L.) and Soybean (<i>Glycine max</i> L.) in North Dakota",
        authors: "Chowdhury IA",
        journal: "<em>PhD Thesis, North Dakota State University, Fargo, ND, USA</em>",
        year: 2020,
        url: "https://www.proquest.com/docview/2479795157?fromopenview=true&pq-origsite=gscholar&sourcetype=Dissertations%20&%20Theses"
      }
    ]
  }
];



const conferences = [
  {
    title: "Artificial intelligence for soybean cyst nematode egg detection and quantification",
    authors: "Omotosho J, <strong>Singh G</strong>, Plaisance A, and Yan G",
    conference: "<i>2026 NDSU Soybean Symposium</i>, North Dakota State University (NDSU), Fargo, ND",
    year: 2026,
    url: "",
    abstract: "Soybean cyst nematode (SCN; <i>Heterodera glycines</i>) is the most economically damaging disease of soybean in the United States, causing an estimated $1.5 billion in annual yield losses. Accurate quantification of SCN egg populations is essential for assessing infestation severity, evaluating host resistance, and guiding management decisions. However, manual microscopic counting methods are labor-intensive, time-consuming, and prone to human error. To address these limitations, we developed a deep learning-based object detection framework using the YOLO (You Only Look Once) model to automate the detection and quantification of SCN eggs from microscopic images. Images were obtained from 35 field-derived and 51 greenhouse-derived SCN samples, from which 501 microscopic images (40-100×) were taken and manually annotated to include eggs, debris, root fragments, and vermiform nematode structures. Image preprocessing and data augmentation expanded the dataset to 4,820 images, improving model robustness to debris variability and generalization to new/unseen sample conditions. The dataset was used to train and evaluate a YOLOv11 model, with performance assessed using mean Average Precision (mAP) and detection accuracy. The model achieved robust egg detection across samples, with an overall detection accuracy of 96.8% and a multi-class mAP@0.5 of 75%. AI (artificial intelligence)-predicted egg counts showed positive correlation (r) with manual counts on unseen test images, ranging from 0.65 in debris-rich field samples to 0.99 in laboratory-cleaned samples. The results demonstrate the great potential of AI tool application to improve the speed, consistency, and scalability of SCN egg quantification, while highlighting the need for further validation under diverse field conditions prior to routine diagnostic deployment.",
    citingPapers: []
  },
  {
    title: "High-quality T2T genomes of spring wheat cultivars Boost and Timstein provide cultivar-resolved frameworks for wheat disease resistance genetics",
    authors: "Singh J, Gudi S, Maughan PJ, Seneviratne S, <strong>Singh G</strong>, Running KLD, Acharya K, Green AJ, Glover K, Faris JD, and Gupta R",
    conference: "<i>Plant and Animal Genome XXXIII (PAG 33)</i> Conference, San Diego, California",
    year: 2026,
    url: "",
    abstract: "Wheat has shaped human civilization and remains central to human society. It fulfills nearly 20% of global dietary caloric intake. The development of genomic resources has accelerated wheat improvement for yield, nutritional quality, and tolerance to biotic and abiotic stresses. Here, we generated near telomere-to-telomere (T2T), high quality genome assemblies for two spring wheat cultivars with contrasting disease-response profiles, Boost and Timstein. Boost exhibits robust bacterial leaf streak resistance, while Timstein has been central to classical genetic studies of stem rust and leaf rust resistance, and carries susceptibility genes for <i>Parastagonospora nodorum</i>, the causal agent of Septoria nodorum blotch. We used ~25x PacBio HiFi sequencing combined with Hi-C scaffolding to generate chromosome level assemblies for these two cultivars. The assemblies span 14.58 Gb (Boost) and 14.76 Gb (Timstein), resolving all 21 chromosomes across three sub-genomes (A, B, and D). Both genomes comprise ~85% transposable elements, primarily Gypsy, Copia, and CACTA families. Gene annotation identified ~103,000 high-confidence gene models in each assembly. The BUSCO analysis showed 97.4-99.6% completeness across individual sub-genomes. Comparative genomics analysis against IWGSC RefSeq v2.1 revealed high chromosomal collinearity in both genomes. We also detected a ~70 Mb terminal deletion on Boost chromosome 7A. These assemblies establish cultivar-resolved genomic frameworks that will accelerate fine mapping of disease resistance and susceptibility loci. The integration of these genomes into the wheat pangenome can enhance understanding of effector-target interactions, unique R-gene architectures, and the genomic basis of host-pathogen adaptation. Together, Boost and Timstein provide powerful resources for advancing wheat disease resistance genetics and translational breeding.",
    citingPapers: []
  },
  {
    title: "Development and validation of SNP-based KASP markers for detection of rare earliness <i>Hope-FTB1</i> gene and mapping of novel genetic loci for yield component traits in hard red spring wheat (<i>Triticum aestivum</i> L.)",
    authors: "Kumari P, Peters Haugrud AR, Seneviratne S, Acharya K, <strong>Singh G</strong>, Xu SS, Zhang Q, Green AJ, and Faris JD",
    conference: "<i>CANVAS 2025</i>, Salt Lake City, Utah",
    year: 2025,
    url: "https://scisoc.confex.com/scisoc/2025am/meetingapp.cgi/Paper/170320",
    abstract: "Wheat (<i>Triticum aestivum</i> L.) feeds over 40% of the global population, and improving grain yield under variable environments remains a critical breeding objective. Yield is significantly impacted by fluctuating climatic conditions, and under such stress-prone environments, early heading (earliness) serves as an effective strategy to escape terminal stress. To dissect the genetic basis of earliness, we developed a Recombinant Isogenic lines (RILs) mapping population derived from a cross between a mid- to late-heading hard red spring wheat (HRSW) cultivar ‘Faller’ and an extremely early-heading Chinese variety ‘Jianquing-5’. A stable and robust QTL for heading date was identified on chromosome 7B, explaining 28% of the phenotypic variation, where a candidate gene, <i>HopeFT-B1</i>, was localized. The <i>HopeFT-B1</i> allele is associated with accelerated flowering and early heading. A highly efficient high-throughput diagnostic marker, <i>fcp1076</i>, was developed for this rare allele. Additionally, a total of 35 stable QTLs were identified for key yield component traits, including kernels per spike (KPS) on chromosomes 2A and 4A, total number of spikes (TNS) on 2A, 4A, and 7B, kernel parameters on 5A, and plant height on 4B. The stable genomic regions associated with yield traits and the <i>HopeFT-B1</i> diagnostic marker linked to earliness together provide robust tools for wheat improvement. These resources enable breeders to simultaneously enhance yield stability and accelerate flowering through efficient marker-assisted selection.",
    citingPapers: []
  },
  {
    title: "Genome-wide association study to identify genomic regions associated with resistance to soybean cyst nematode HG type 2.5.7 in dry beans",
    authors: "Singh D, Poudyal P, <strong>Singh G</strong>, Neupane R, Cerna JF, Osorno JM, and Yan G",
    conference: "<i>International Bean Improvement Cooperative (BIC) and North American Pulse Improvement Association (NAPIA)</i> Biennial Meeting, Lincoln, Nebraska",
    year: 2025,
    url: "https://agronomy.unl.edu/bic-napia-speakers/#:~:text=Gurminder%20Singh",
    abstract: "Soybean cyst nematode (SCN; <i>Heterodera glycines</i> Ichinohe) is the most destructive pathogen of soybean [<i>Glycine max</i> (L.) Merr.], causing substantial yield losses in the US. Recent reports have shown that SCN can also reproduce on dry bean (<i>Phaseolus vulgaris</i> L.), raising concerns that dry bean could become an additional host crop with similar yield risks. In North Dakota and the upper Midwest regions, where both soybean and dry bean are important crops, the spread of virulent SCN populations represents a growing threat. Among these, HG type 2.5.7 is of particular concern because it can reproduce on PI 88788-derived resistance (the predominant source used in soybean) and become prevalent in surveyed fields in North Dakota. Host resistance is well established as an effective and eco-friendly management strategy in soybean; however, in dry beans, resistant sources are poorly characterized and used. In this study, we evaluated 263 dry bean genotypes spanning the Middle American and Andean gene pools and multiple market classes (great northern, black, navy, slow-darkening pinto, light red kidney, dark red kidney). Two independent greenhouse experiments were conducted using HG type 2.5.7, and SCN infection was quantified as the female index (FI) relative to the susceptible soybean check ‘Barnes’. Phenotypic responses across experiments were estimated using best linear unbiased predictions (BLUPs). Genotyping was performed with a newly developed custom 3.8K Bean Panel Chip. After quality control, 2,019 single-nucleotide polymorphism (SNP) markers were retained and evenly distributed across the 11 dry bean chromosomes. A genome-wide association study was conducted in GAPIT using the BLINK model, with quantile-quantile (QQ) plots confirming appropriate model fit. Two significant SNP-trait associations were identified: <i>S02_50534194</i> on chromosome Pv2, which explained 57.88% of the phenotypic variance, and <i>S07_37564475</i> on Pv7, which explained 1.84%. These marker-trait associations point to genomic regions that may underlie resistance to HG type 2.5.7 in dry bean and provide a foundation for candidate gene discovery. This study provides a basis for developing high-throughput markers to support marker-assisted and genomic selection to expedite the breeding of dry bean cultivars with improved resistance to SCN.  ",
    citingPapers: []
  },
  {
    title: "Genomic and functional characterization of an <i>Exo70-like</i> gene governing susceptibility to tan spot in wheat",
    authors: "<strong>Singh G</strong>, Running K, Seneviratne S, Acharya K, Roth T, Haugrud A, Zhang Z, Szabo-Hever A, Kumari P, Liu Z, and Faris JD",
    conference: "<i>Corteva New Frontiers: Innovation in Genome Editing: Algorithms to On-Farm Solutions</i> Meeting, Johnston, Iowa",
    year: 2025,
    url: "",
    abstract: "Tan spot, caused by the necrotrophic fungus <i>Pyrenophora tritici-repentis</i>, leads to significant yield losses in wheat worldwide. The fungal effector Ptr ToxB interacts with the wheat susceptibility gene <i>Tsc2</i>, inducing chlorosis and reducing photosynthetic activity. This study aimed to identify and functionally characterize <i>Tsc2</i> to enhance understanding of this host-pathogen interaction. We mapped the <i>Tsc2</i> locus using a biparental population derived from a cross between durum wheat cultivars Kronos (Ptr ToxB-sensitive) and Gredho (insensitive). High-resolution mapping was conducted in an F<sub>2</sub> population of 1,490 individuals (Kronos × Gredho) using KASP markers designed from exome capture data, narrowing <i>Tsc2</i> to a 108-kb interval on chromosome arm 2BS containing ten candidate genes. Comparative genomics across ten wheat genome assemblies revealed that two genes, an <i>Exo70</i> and an <i>LRR-Protein Kinase</i>, were present exclusively in sensitive genotypes. Sequencing of Kronos TILLING mutants and Ptr ToxB-insensitive EMS mutants of the cultivar Prosper identified mutations in Exo70 correlating with insensitivity, implicating it as the candidate <i>Tsc2</i> gene. Functional validation is underway through genetic complementation using <i>Agrobacterium</i>-mediated transformation of insensitive genotypes (Bobwhite and Fielder) with the wild-type <i>Exo70</i> gene and CRISPR/Cas9-mediated gene knockouts. Additionally, yeast two-hybrid assays are being conducted to elucidate the interaction between Exo70 and Ptr ToxB. The identification and functional characterization of <i>Exo70</i> advances our understanding of the molecular mechanisms underlying wheat susceptibility to tan spot. We developed a high-throughput marker for the absent <i>Tsc2</i> allele, efficiently predicting Ptr ToxB-insensitive lines in durum and spring wheat, facilitating marker-assisted elimination of <i>Tsc2</i>.",
    citingPapers: []
  },
  {
    title: "Genomic and functional characterization of an <i>Exo70-like</i> gene governing susceptibility to tan spot in wheat",
    authors: "<strong>Singh G</strong>, Running K, Seneviratne S, Acharya K, Roth T, Haugrud A, Zhang Z, Szabo-Hever A, Kumari P, Liu Z, and Faris JD",
    conference: "<i>2025 National Association of Plant Breeders (NAPB)</i> Meeting, Kona, Big Island, Hawaii",
    year: 2025,
    url: "https://napbannualmeeting.org/wp-content/uploads/2025/05/NAPB_2025_Booklet_Digital_VF2.pdf",
    abstract: "Tan spot, caused by the necrotrophic fungus <i>Pyrenophora tritici-repentis</i>, leads to significant yield losses in wheat worldwide. The fungal effector Ptr ToxB interacts with the wheat susceptibility gene <i>Tsc2</i>, inducing chlorosis and reducing photosynthetic activity. This study aimed to identify and functionally characterize <i>Tsc2</i> to enhance understanding of this host-pathogen interaction. We mapped the <i>Tsc2</i> locus using a biparental population derived from a cross between durum wheat cultivars Kronos (Ptr ToxB-sensitive) and Gredho (insensitive). High-resolution mapping was conducted in an F<sub>2</sub> population of 1,490 individuals (Kronos × Gredho) using KASP markers designed from exome capture data, narrowing <i>Tsc2</i> to a 108-kb interval on chromosome arm 2BS containing ten candidate genes. Comparative genomics across ten wheat genome assemblies revealed that two genes, an <i>Exo70</i> and an <i>LRR-Protein Kinase</i>, were present exclusively in sensitive genotypes. Sequencing of Kronos TILLING mutants and Ptr ToxB-insensitive EMS mutants of the cultivar Prosper identified mutations in Exo70 correlating with insensitivity, implicating it as the candidate <i>Tsc2</i> gene. Functional validation is underway through genetic complementation using <i>Agrobacterium</i>-mediated transformation of insensitive genotypes (Bobwhite and Fielder) with the wild-type <i>Exo70</i> gene and CRISPR/Cas9-mediated gene knockouts. Additionally, yeast two-hybrid assays are being conducted to elucidate the interaction between Exo70 and Ptr ToxB. The identification and functional characterization of <i>Exo70</i> advances our understanding of the molecular mechanisms underlying wheat susceptibility to tan spot. We developed a high-throughput marker for the absent <i>Tsc2</i> allele, efficiently predicting Ptr ToxB-insensitive lines in durum and spring wheat, facilitating marker-assisted elimination of <i>Tsc2</i>.",
    citingPapers: []
  },
  {
    title: "Genomic and functional characterization of an <i>Exo70-like</i> gene governing susceptibility to tan spot in wheat",
    authors: "<strong>Singh G</strong>, Running K, Seneviratne S, Acharya K, Roth T, Haugrud A, Zhang Z, Szabo-Hever A, Kumari P, Liu Z, and Faris JD",
    conference: "<i>Bayer Crop Science - Bring Them In</i> Event, Chesterfield, Missouri",
    year: 2025,
    url: "",
    abstract: "Tan spot, caused by the necrotrophic fungus <i>Pyrenophora tritici-repentis</i>, leads to significant yield losses in wheat worldwide. The fungal effector Ptr ToxB interacts with the wheat susceptibility gene <i>Tsc2</i>, inducing chlorosis and reducing photosynthetic activity. This study aimed to identify and functionally characterize <i>Tsc2</i> to enhance understanding of this host-pathogen interaction. We mapped the <i>Tsc2</i> locus using a biparental population derived from a cross between durum wheat cultivars Kronos (Ptr ToxB-sensitive) and Gredho (insensitive). High-resolution mapping was conducted in an F<sub>2</sub> population of 1,490 individuals (Kronos × Gredho) using KASP markers designed from exome capture data, narrowing <i>Tsc2</i> to a 108-kb interval on chromosome arm 2BS containing ten candidate genes. Comparative genomics across ten wheat genome assemblies revealed that two genes, an <i>Exo70</i> and an <i>LRR-Protein Kinase</i>, were present exclusively in sensitive genotypes. Sequencing of Kronos TILLING mutants and Ptr ToxB-insensitive EMS mutants of the cultivar Prosper identified mutations in Exo70 correlating with insensitivity, implicating it as the candidate <i>Tsc2</i> gene. Functional validation is underway through genetic complementation using <i>Agrobacterium</i>-mediated transformation of insensitive genotypes (Bobwhite and Fielder) with the wild-type <i>Exo70</i> gene and CRISPR/Cas9-mediated gene knockouts. Additionally, yeast two-hybrid assays are being conducted to elucidate the interaction between Exo70 and Ptr ToxB. The identification and functional characterization of <i>Exo70</i> advances our understanding of the molecular mechanisms underlying wheat susceptibility to tan spot. We developed a high-throughput marker for the absent <i>Tsc2</i> allele, efficiently predicting Ptr ToxB-insensitive lines in durum and spring wheat, facilitating marker-assisted elimination of <i>Tsc2</i>.",
    citingPapers: []
  },
  {
    title: "Genomic and functional characterization of an <i>Exo70-like</i> gene governing susceptibility to tan spot in wheat",
    authors: "<strong>Singh G</strong>, Running K, Seneviratne S, Acharya K, Roth T, Haugrud A, Zhang Z, Szabo-Hever A, Kumari P, Liu Z, and Faris JD",
    conference: "<i>Plant and Animal Genome XXXII (PAG 32)</i> Conference, San Diego, California",
    year: 2025,
    url: "https://plan.core-apps.com/pag32/abstract/0d2898dc-9da9-49f8-8f92-e5c77817cf59",
    abstract: "Tan spot, caused by the necrotrophic fungus <i>Pyrenophora tritici-repentis</i>, leads to significant yield losses in wheat worldwide. The fungal effector Ptr ToxB interacts with the wheat susceptibility gene <i>Tsc2</i>, inducing chlorosis and reducing photosynthetic activity. This study aimed to identify and functionally characterize <i>Tsc2</i> to enhance understanding of this host-pathogen interaction. We mapped the <i>Tsc2</i> locus using a biparental population derived from a cross between durum wheat cultivars Kronos (Ptr ToxB-sensitive) and Gredho (insensitive). High-resolution mapping was conducted in an F<sub>2</sub> population of 1,490 individuals (Kronos × Gredho) using KASP markers designed from exome capture data, narrowing <i>Tsc2</i> to a 108-kb interval on chromosome arm 2BS containing ten candidate genes. Comparative genomics across ten wheat genome assemblies revealed that two genes, an <i>Exo70</i> and an <i>LRR-Protein Kinase</i>, were present exclusively in sensitive genotypes. Sequencing of Kronos TILLING mutants and Ptr ToxB-insensitive EMS mutants of the cultivar Prosper identified mutations in Exo70 correlating with insensitivity, implicating it as the candidate <i>Tsc2</i> gene. Functional validation is underway through genetic complementation using <i>Agrobacterium</i>-mediated transformation of insensitive genotypes (Bobwhite and Fielder) with the wild-type <i>Exo70</i> gene and CRISPR/Cas9-mediated gene knockouts. Additionally, yeast two-hybrid assays are being conducted to elucidate the interaction between Exo70 and Ptr ToxB. The identification and functional characterization of <i>Exo70</i> advances our understanding of the molecular mechanisms underlying wheat susceptibility to tan spot. We developed a high-throughput marker for the absent <i>Tsc2</i> allele, efficiently predicting Ptr ToxB-insensitive lines in durum and spring wheat, facilitating marker-assisted elimination of <i>Tsc2</i>.",
    citingPapers: []
  },
  {
    title: "Characterization of wheat genes governing sensitivity to the <i>Parastagonospora nodorum</i> necrotrophic effector SnTox5",
    authors: "Running K, Sharma S, Seneviratne S, Poddar S, Szabo-Hever A, Haugrud A, Pfaff T, <b>Singh G</b>, Acharya K, Kariyawasam G, Zhang Z, Staskawicz BJ, Xu SS, Friesen TL, and Faris JD",
    conference: "<i>International Symposium on Cereal Leaf Blight</i>, Zurich, Switzerland",
    year: 2024,
    url: "",
    abstract: "The necrotrophic fungal pathogen <i>Parastagonospora nodorum</i> produces necrotrophic effectors (NEs) that target specific genes in wheat to cause the disease septoria nodorum blotch (SNB). The interaction between the NE SnTox5 and the wheat gene <i>Snn5</i> plays a significant role in the development of SNB. Snn5 was previously mapped to chromosome arm 4BL. Here, we combined positional cloning, TILLING, and gene editing approaches to clone Snn5. Snn5 encodes a protein with protein kinase and major sperm protein (PK-MSP) domains. Analysis of <i>Snn5</i>-disrupted mutants indicated that both major domains are essential for function. Through related genetic experiments, we identified a second SnTox5-sensitivity locus on chromosome arm 2BS. This gene was delineated to an 8.54 cM interval corresponding to a 9.6 Mb region in Svevo Rel 1.0 containing six PK-MSP-like genes. Given the presence of multiple SnTox5 sensitivity genes, we propose that the original sensitivity gene be termed <i>Snn5-B1</i> and the second sensitivity gene mapped to chromosome 2B be termed <i>Snn5-B2</i>. Genome-wide association studies on large panels of durum and common wheat indicated that <i>Snn5-B1</i> was predominant among common wheat accessions whereas <i>Snn5-B2</i> was relatively more frequent among durum lines. This research extends our knowledge of the <i>Snn5</i>-SnTox5 interaction and the wheat-<i>P. nodorum</i> system in general, and provides tools to aid in the development of SNB-resistant wheat via marker-assisted selection and gene editing.",
    citingPapers: []
  },
  {
    title: "Molecular cloning of the septoria nodorum blotch susceptibility gene <i>Snn2</i> in wheat",
    authors: "Seneviratne S, Zhang Z, Running K, Peters Haugrud AR, Szabo-Hever A, <strong>Singh G</strong>, Acharya K, Fiedler JD, Mclean P, Xu SS, Yang S, Friesen TL, and Faris JD",
    conference: "<i>Plant and Animal Genome XXXI (PAG 31)</i> Conference, San Diego, California",
    year: 2024,
    url: "https://www.ars.usda.gov/research/publications/publication/?seqNo115=410372",
    abstract: "Septoria nodorum blotch (SNB) of wheat is a destructive foliar and glume disease caused by the necrotrophic fungal pathogen <i>Parastagonospora nodorum</i>. The disease is initiated by the recognition of pathogen-produced necrotrophic effectors (NEs) by dominant host sensitivity genes in wheat in an inverse gene-for-gene manner. Multiple host sensitivity genes and NEs have been identified in this pathosystem, and some NEs interact with more than one host sensitivity gene. <i>Snn2</i>, which is located on the chromosome 2DS, is the first host gene that was found to be interacting with the necrotrophic effector SnTox267. The objective of this study is to clone and characterize the Snn2 gene. Towards the molecular cloning of <i>Snn2</i>, a saturated genetic linkage map was constructed using a segregating population of 164 F<sub>7:8</sub> recombinant inbred lines. The map was saturated with markers identified through SNP genotyping using the 90K iSelect wheat SNP chip, as well as simple sequence repeat (SSR) markers developed based on whole-genome sequence scaffolds, wheat survey sequences, and the IWGSC RefSeq v1.0 reference genome. A high-resolution map was then developed using an F<sub>2</sub> population derived from a cross between the SnTox267-insensitive wheat line BR34 and the SnTox267-sensitive line BG301. Over 10,000 gametes were screened for high resolution mapping, and <i>Snn2</i> was delineated to a genetic interval of 0.58 cM, which corresponds to a physical segment of 0.96 Mb on Chinese Spring reference genome. A total of 45 high confidence genes were identified in this region, which included eight NB-ARC domain-containing genes and ten protein kinase (PK)-containing genes. Analyses of EMS-induced SnTox267-insensitive mutants and genome-wide association studies indicated that one of the PK-major sperm protein (PK-MSP) genes is a strong candidate for Snn2. CRISPR/Cas9-mediated gene editing revealed that the inactivation of this candidate gene can transform the sensitive wheat variety Bobwhite to become insensitive to SnTox267, confirming it as the <i>Snn2</i> gene. Currently, a gene complementation experiment is being carried out to further validate the cloning of Snn2. Additionally, work is in progress to characterize <i>Snn2</i> and other SnTox267-sensitivity genes. The findings of this study increase our understanding of wheat-<i>P. nodorum</i> pathosystem and will help to develop better host resistance against SNB through genetic manipulation.",
    citingPapers: []
  },
  {
    title: "Molecular mapping of a novel genetic locus governing enhanced susceptibility to tan spot in durum wheat",
    authors: "Pfaff T, <strong>Singh G</strong>, Running K, Szabo-Hever A, and Faris JD",
    conference: "<i>Plant and Animal Genome XXXI (PAG 31)</i> Conference, San Diego, California",
    year: 2024,
    url: "https://www.ars.usda.gov/research/publications/publication/?seqNo115=410373",
    abstract: "Tan spot is an important foliar disease in wheat caused by the fungal pathogen <i>Pyrenophora tritici-repentis</i> (Died.) Drechs. (Ptr). The wheat-Ptr pathosystem follows an inverse gene-for-gene model where pathogen-produced necrotrophic effectors (NEs) are recognized by dominant host genes resulting in host-induced programmed cell death, which leads to disease in the plant. The NE Ptr ToxB is recognized by the gene <i>Tsc2</i>, which results in a compatible interaction that leads to induction of chlorosis in both durum and common wheat. In genome wide association studies (GWAS) on the Global Durum Panel, we observed that infiltration of Ptr ToxB into leaves of some wheat lines showed an expansion of chlorosis outside the infiltrated area to the distal end of the leaf, and this expansion was associated with increased disease severity. The locus responsible for chlorosis expansion, which we have designated as <i>Tsc3</i>, was located on chromosome arm 5BL in durum wheat. To precisely map the <i>Tsc3</i> locus and initiate map-based cloning of the gene, we developed an F2 population derived from durum varieties Kronos and Simeto. Kronos and Simeto are sensitive to Ptr ToxB, but only Simeto expresses expansion of chlorosis outside the infiltration site. Initial low-resolution mapping was completed using 342 F2 plants and 9 KASP markers developed from the polymorphic SNPs identified in the Infinium iSelect 90K SNP array. For saturation mapping, an additional 15 KASP markers were designed from polymorphic SNPs identified by alignment of genes annotated in the Svevo.v1 reference assembly to the Kronos scaffold assemblies and a Simeto assembly. Using 675 F<sub>2</sub> plants and the 24 KASP markers, we have delineated the Tsc3 locus to a 1.1 cM interval and identified nine markers that cosegregate with the gene. The Tsc3 locus resides within a 3.2 Mb physical interval on chromosome arm 5BL in the Svevo.v1 reference genome, which contains about 40 high-confidence genes. High-resolution mapping of the locus using approximately 2,300 F<sub>2</sub> plants has been initiated to resolve the markers and further narrow the candidate gene interval. In addition, an ethylmethane-sulfonate (EMS)-induced mutant population is currently being developed to identify putative <i>Tsc3</i>-disrupted mutants for gene validation. This work will shed light on the molecular mechanisms operating in the wheat-Ptr pathosystem and aid in the development of new strategies to develop tan spot resistant wheat. ",
    citingPapers: []
  },
  {
    title: "Molecular cloning and validation of candidate genes for the tan spot susceptibility locus <i>Tsc2</i> in wheat",
    authors: "<strong>Singh G</strong>, Running K, Haugrud A, Seneviratne S, Zhang Z, Szabo-Hever A, Acharya K, Liu Z, and Faris JD",
    conference: "<i>ASA, CSSA, SSSA International Annual Meeting</i>, St. Louis, Missouri",
    year: 2023,
    url: "https://scisoc.confex.com/scisoc/2023am/meetingapp.cgi/Paper/148627",
    abstract: "Tan spot, a prevalent foliar disease caused by the necrotrophic fungus <i>Pyrenophora tritici-repentis</i>, causes significant yield losses in wheat worldwide. The <i>Tsc2</i> locus on chromosome arm 2BS in wheat recognizes the fungal necrotrophic effector Ptr ToxB. The <i>Tsc2</i>-Ptr ToxB interaction triggers chlorosis, which leads to decreased photosynthetic activity, plant stress, and ultimately yield loss. In this study, we used a durum wheat recombinant inbred line population derived from a cross between Kronos (sensitive to Ptr ToxB) and Gredho (insensitive), along with a diverse hard red spring wheat panel, to precisely map the <i>Tsc2</i> locus. To saturate the <i>Tsc2</i> genomic region, KASP markers were designed using exome capture data from Kronos and Gredho. High-resolution mapping of these molecular markers delineated the <i>Tsc2</i> locus to a 0.13 cM interval in an F<sub>2</sub> population (Kronos × Gredho) consisting of 2,980 gametes. Based on the genome assembly of the durum wheat cultivar Simeto, the interval was 108.48 kb in size and harbored ten candidate genes. These genes were interrogated using a reverse genetics approach with the Kronos TILLING mutants. We also developed an ethyl methanesulfonate (EMS)-induced mutant population of Prosper, and screening of M<sub>2</sub> families led to the identification of multiple Ptr ToxB-insensitive mutants. Comparative sequence analysis of multiple Kronos and Prosper EMS mutants revealed a single candidate gene as <i>Tsc2</i> and is currently being further validated by genetic complementation. Transcription expression levels, allelic diversity, and functional analysis of the gene are also being conducted. The findings of this study will expedite the functional characterization of the <i>Tsc2</i> gene, enhance our understanding of the wheat-<i>P. tritici-repentis</i> interaction, and aid in developing diagnostic genetic markers for breeding programs to mitigate tan spot in wheat.",
    citingPapers: []
  },
  {
    title: "Development of diagnostic molecular markers for the multi-pathogen susceptibility gene <i>Tsn1</i>",
    authors: "Running K, Pfaff T, <strong>Singh G</strong>, Szabo-Hever A, Peters Haugrud A, Zhang Z, Seneviratne S, McClean PE, Fiedler JD, Friesen TL, and Faris JD",
    conference: "<i>Plant and Animal Genome XXX (PAG 30)</i> Conference, San Diego, California",
    year: 2023,
    url: "https://www.ars.usda.gov/research/publications/publication/?seqNo115=399522",
    abstract: "The Tsn1 gene confers sensitivity to the necrotrophic effector ToxA, which is produced by necrotrophic fungal pathogens that cause the foliar diseases tan spot, septoria nodorum blotch, and spot blotch. Codominant microsatellite markers that delineate <i>Tsn1</i> to 351 kb were developed previously, but they are not amenable to high-throughput genotyping (HTG), and their efficacy was not evaluated. Here, the published genome assemblies of fifteen bread wheat, two durum wheat, and one wild emmer wheat accessions were used to compare gene and transposable element content in Tsn1- and Tsn1+ lines, revealing two conserved haplotypes. Because <i>Tsn1</i> is almost always null in insensitive cultivars, conserved KASP markers suitable for HTG were designed in the closest syntenic region between Tsn1- and Tsn1+ assemblies. The flanking KASP markers delineated Tsn1 to 135 kb and were validated on over 1,500 diverse lines. Phenotyping of the lines revealed that the markers correctly predicted a ToxA insensitive phenotype in 99.13-100% of the accessions. The KASP markers were less effective at predicting a ToxA sensitive phenotype (88.68-94.17%) due to a preponderance of insensitive lines with sensitive marker alleles. Sequencing analysis of Tsn1 from these lines revealed some carried nonfunctional alleles, while others carried the dominant <i>Tsn1</i> allele. Future expression analysis and genetic mapping will elucidate the nature of the ToxA insensitive status in lines with the Tsn1 allele. The markers presented here could be used for reliable and robust marker-assisted elimination of Tsn1, furthering the development of wheat genetically resistant to multiple pathogens. ",
    citingPapers: []
  },
  {
    title: "Towards the molecular cloning of tan spot susceptibility gene <i>Tsc2</i> in wheat",
    authors: "<strong>Singh G</strong>, Running K, Peters Haugrud A, Seneviratne S, Zhang Z, Szabo-Hever A, Acharya K, Liu Z, Dubcovsky J, and Faris JD",
    conference: "<i>Plant and Animal Genome XXX (PAG 30)</i> Conference, San Diego, California",
    year: 2023,
    url: "https://www.ars.usda.gov/research/publications/publication/?seqNo115=399524",
    abstract: "Tan spot, caused by the necrotrophic fungal pathogen <i>Pyrenophora tritici-repentis</i>, is an important foliar disease that causes significant yield losses in wheat worldwide. The <i>Tsc2</i> locus on chromosome arm 2BS in wheat recognizes the necrotrophic effector Ptr ToxB to induce a compatible response leading to chlorosis and loss of photosynthetic area on infected wheat leaves, which leads to plant stress and yield loss. In this study, a durum wheat bi-parental population derived from a cross between Kronos (sensitive to Ptr ToxB) and Gredho (insensitive) and a large hard red spring wheat panel were used to delimited the <i>Tsc2</i> locus to a genetic distance of 1.41 cM, which corresponded to a physical region of 1.37 Mb. The candidate gene region contained 27 putative genes based on the durum wheat reference sequence from Svevo (insensitive to Ptr ToxB). KASP markers were designed to saturate the <i>Tsc2</i> region using exome capture data from Kronos and Gredho. The molecular markers developed in this study are currently being used for high-resolution mapping of the <i>Tsc2</i> locus in a large F<sub>2</sub> (Kronos × Gredho) population, and candidate genes are being evaluated in several mutant populations. Results from this study will help us clone the <i>Tsc2</i> gene, gain knowledge and insights regarding the wheat-<i>P. tritici-repentis</i> pathosystem, and develop diagnostic genetic markers to be used in breeding programs to combat tan spot in wheat.",
    citingPapers: []
  },
  {
    title: "Genome-wide association mapping of resistance to the foliar diseases septoria nodorum blotch and tan spot in a global winter wheat (<i>Triticum aestivum</i> L.) collection",
    authors: "Peters Haugrud A, Shi G, Seneviratne S, Running K, Zhang Z, <strong>Singh G</strong>, Szabo-Hever A, Acharya K, Friesen TL, Liu Z, and Faris JD",
    conference: "<i>Plant and Animal Genome XXX (PAG 30)</i> Conference, San Diego, California",
    year: 2023,
    url: "https://www.ars.usda.gov/research/publications/publication/?seqNo115=399529",
    abstract: "Septoria nodorum blotch (SNB) and tan spot, caused by the necrotrophic fungal pathogens <i>Parastagonospora nodorum</i> and <i>Pyrenophora tritici-repentis</i>, respectively, are major foliar diseases on wheat (<i>Triticum aestivum</i> L.). Both pathogens produce necrotrophic effectors (NEs) that are known to play significant roles in the development of disease. We evaluated a panel of 264 winter wheat lines representing a large proportion of the global genetic diversity. We found that 38.6, 4.3, 36.7, 39.0, 48.9, and 42.4 % of the lines were sensitive to the NEs Sn/Ptr ToxA, Ptr ToxB, SnTox1, SnTox267, SnTox3, and SnTox5, respectively. We inoculated the panel with fungal spores of five <i>P. nodorum</i> isolates and four <i>P. tritici-repentis</i> isolates and performed genome-wide association mapping to identify genomic regions associated with disease. For SNB, the Snn3-SnTox3 and Tsn1-SnToxA interactions played significant roles in disease development, along with an uncharacterized QTL on chromosome 2A. For tan spot, the <i>Tsc1</i>-Ptr ToxC interaction was associated with disease caused by isolates Pti2 and AR CrossB10, and a novel QTL was identified on chromosome 7D. The <i>Tsn1</i>-ToxA interaction played an important role in SNB development but not in tan spot development. The screening results with purified NEs will be useful for cloning, validation, and marker development of the sensitivity genes <i>Snn3-B1</i>, <i>Snn2</i>, <i>Snn5</i>, <i>Snn6</i>, and <i>Snn7</i>. This work shows the complexity of disease resistance to SNB and tan spot and illustrates that not all of the previously characterized interactions in these pathosystems play a significant role in disease development in winter wheat.",
    citingPapers: []
  },
  {
    title: "Genetic diversity and marker-assisted elimination of <i>Snn1</i> in wheat",
    authors: "Seneviratne S, Shi G, Szabo-Hever A, Zhang Z, Peters Haugrud A, Running K, <strong>Singh G</strong>, Nandety RS, Fiedler JD, Xu SS, Friesen TL, McClean PE, and Faris JD",
    conference: "<i>Plant and Animal Genome XXX (PAG 30)</i> Conference, San Diego, California",
    year: 2023,
    url: "https://www.ars.usda.gov/research/publications/publication/?seqNo115=399503",
    abstract: "Septoria nodorum blotch (SNB) is a severe foliar and glume disease of durum and common wheat characterized by cell death that is initiated by interactions between necrotrophic effectors (NEs) produced by the fungus <i>Parastagonospora nodorum</i> and corresponding host sensitivity genes in wheat. The <i>Snn1</i>-SnTox1 interaction is one of multiple host sensitivity gene-NE interactions identified in the wheat-<i>P. nodorum</i> pathosystem, and it plays a significant role in SNB development. The host sensitivity gene <i>Snn1</i> was previously cloned from wheat, but a diagnostic PCR marker has not been developed. In this study, the allelic diversity of <i>Snn1</i> was studied to identify causal polymorphisms and to develop markers useful for marker-assisted elimination (MAE) of functional <i>Snn1</i> alleles. The full length <i>Snn1</i> gene was sequenced from 99 accessions including diploid, tetraploid, and hexaploid wheat species. Multiple sequence alignments revealed 27 haplotypes based on the coding sequence of the gene. Three mutations that possibly changed the primitive insensitive allele in wild emmer into the sensitive allele in domesticated wheat and four independent SNPs that subsequently changed the sensitive allele into insensitive alleles were identified. These SNPs are within each of the three exons of <i>Snn1</i> affecting multiple domains. Kompetitive allele specific PCR (KASP) markers were developed for three of these mutations and the <i>Snn1</i> null allele. These newly developed markers identify more than 95% of the durum and spring wheat accessions that are sensitive to SnTox1 and can be used for MAE. Results of this study also increase our understanding of the evolution of <i>Snn1</i>.",
    citingPapers: []
  },
  {
    title: "Identification of quantitative trait loci for resistance to <i>Pratylenchus neglectus</i> in triticale",
    authors: "<strong>Singh G</strong>, Yan GP, Liu Z, and Faris JD",
    conference: "<i>7th International Congress of Nematology</i>, Antibes Juan-les-Pins, France",
    year: 2022,
    url: "https://www.esn-online.org/assets/Uploads/meetings/e9d266eb07/Book-of-Abstracts_ICN2022.pdf",
    abstract: "The root-lesion nematode (RLN), <i>Pratylenchus neglectus</i>, is an important pathogen of wheat. Utilizing host resistance is the most economical and environment-friendly way to control this nematode. To date, no RLN- resistant commercial wheat cultivar has been reported, and sources of resistance in wheat are scarce. Previous studies have reported high levels of resistance in rye and triticale. Triticale is a hybrid of wheat and rye, and identifying RLN resistance genes in triticale would be the first step to utilizing triticale resistance in wheat. In this study, a triticale population consisting of 141 recombinant inbred lines (RILs) derived from a cross between Siskiyou (susceptible parent) and Villax St. Jose (moderately resistant parent) was evaluated for reaction to <i>P. neglectus</i> under greenhouse conditions. Our goal was to identify QTL (quantitative trait loci) associated with resistance to RLN. The population was genotyped using genotyping-by-sequencing (GBS) and SSR markers, and a high-density genetic linkage map was constructed covering all wheat and rye chromosomes. Single trait multiple-interval mapping analysis revealed the presence of a single QTL (LOD = 8.6) on rye chromosome 5R that accounted for approximately 24.6% of the total phenotypic variation. The identified QTL needs to be validated in different genetic backgrounds to confirm its stability. The PCR-based molecular markers associated with this QTL will be useful for fine-mapping and to better understand the genetics of RLN resistance. This work provides a foundation for the introgression of rye-derived <i>P. neglectus</i> resistance into wheat germplasm.",
    citingPapers: []
  },
  {
    title: "Identification of QTL associated with resistance to root-lesion nematode (<i>Pratylenchus neglectus</i>) in wheat using genotyping-by-sequencing",
    authors: "<strong>Singh G</strong>, Li X, Smiley R, and Yan GP",
    conference: "<i>APS Plant Health 2019 Annual Meeting</i>, Cleveland, Ohio",
    year: 2019,
    url: "https://doi.org/10.1094/PHYTO-109-10-S2.1",
    abstract: "The root-lesion nematode, <i>Pratylenchus neglectus</i> is one of the major soil-borne pathogens that reduces wheat productivity throughout the world. As very few management practices are available, utilization of host resistance is considered to be the most effective and preferred method to mitigate effects of root-lesion nematode in wheat. Phenotyping of resistance to <i>P. neglectus</i> in wheat is labor- intensive and time-consuming, which is the major constraint in breeding programs to develop resistant cultivars. Molecular marker assisted selection may enhance the process of developing resistant cultivars. An F2:5 recombinant inbred line population was developed from a cross between a soft white spring wheat “Louise” (susceptible parent) and an Iranian landrace “Persia 20” (resistant parent). The recombinant inbred lines were evaluated for <i>P. neglectus</i> resistance reactions under controlled greenhouse conditions, and then were genotyped using genotyping-by-sequencing (GBS). Using Tassel5 GBSv2 Pipeline, a total of 2,427 high-quality SNPs were identified and used to construct a linkage map. We detected one major QTL (LOD = 5.3) showing association with <i>P. neglectus</i> resistance, located on chromosome 4A and accounted for 35.4% of the total phenotypic variation. The SNP markers closely linked with this QTL will be converted to PCR-based markers that may provide an efficient tool to breeders for developing <i>P. neglectus</i>-resistant cultivars using marker-assisted selection.",
    citingPapers: []
  },
  {
    title: "Methodology to study the resistance of root-lesion nematode (<i>Pratylenchus neglectus</i>) in wheat under greenhouse conditions",
    authors: "<strong>Singh G</strong> and Yan GP",
    conference: "<i>APS North Central Divison Meeting</i>, Fargo, North Dakota",
    year: 2018,
    url: "https://doi.org/10.1094/PHYTO-108-12-S2.20",
    abstract: "The root-lesion nematode (RLN; <i>Pratylenchus neglectus</i>) is one of the important plant-parasitic nematodes which invade the roots of wheat and cause yield losses throughout the world. Resistance of wheat cultivars against RLN is traditionally evaluated by measuring reproductive factor (RF) which is calculated by dividing the final nematode population density by the initial population density. However, RF is affected by several factors, such as plant growth period in greenhouse, and soil texture. The objective of this study was to evaluate the effects of these factors on RF. In one experiment, field soil naturally infested with <i>P. neglectus</i> was used to infect wheat plants, and nematodes were extracted at 8, 10, 12, 14, and 16 weeks after planting using Whitehead Tray method. In another experiment, the wheat was grown in two different soil types including sandy and sandy loam soil which were artificially inoculated with 300 <i>P. neglectus</i>/150 g of soil with five replications. A maximum plant root mass and nematode RF of 16 were obtained at 14 weeks after planting. Sandy soil, having RF of 8, had significantly greater reproduction than sandy loam soil (RF = 1). Using sandy soil and harvesting at 14 weeks after planting produced the best results. This improved methodology will facilitate resistance screening of wheat germplasm or varieties against RLN under greenhouse conditions.",
    citingPapers: []
  }
];

